version: '3'
services:
  app:
    container_name: php71
    image: php:7.1-apache
    volumes:
      - ".:/var/www/html"
      - "./000-default.conf:/etc/apache2/sites-enabled/000-default.conf"
    ports:
      - 80:80
  mysql:
    container_name: mysql
    image: mysql
    platform: linux/x86_64
    environment:
        MYSQL_ROOT_PASSWORD: 123456
    ports:
        - 3306:3306
    restart: always

  # phpmyadmin:
  #   image: phpmyadmin
  #   links:
  #     - mysql
  #   ports:
  #     - 81:80
  #   environment:
  #     - "MYSQL_USER:root"
  #     - "PMA_ARBITRARY:1"
  phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin
      depends_on:
        - mysql
      restart: always
      ports:
        - 81:80
      environment:
        MYSQL_USERNAME: root
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: 123456
        # PMA_ARBITRARY: 1
